const translations = {
    'en': {
        'nav_home': 'Home',
        'nav_doctors': 'Find Doctors',
        'nav_appointments': 'Appointments',
        'nav_contact': 'Contact',
        'nav_login': 'Login',
        'nav_signup': 'Sign Up',
        'nav_book': 'Book Appointment',
        'hero_title': 'Your Health, <span>Our Priority</span>',
        'hero_subtitle': 'Connect with top-rated doctors and book appointments in seconds. Your journey to better health starts here.',
        'btn_get_started': 'Get Started',
        'btn_how_it_works': 'How It Works',
        'stat_doctors': 'Verified Doctors',
        'stat_patients': 'Happy Patients',
        'stat_rating': 'Avg Rating',
        'section_features_title': 'Why Choose DocConnect?',
        'section_features_subtitle': 'We provide the most seamless and secure healthcare experience for both patients and doctors.',
        'feature_1_title': 'Smart AI Chatbot',
        'feature_1_desc': 'Get instant answers to your medical queries and find the right doctor using our AI assistant.',
        'feature_2_title': 'Easy Scheduling',
        'feature_2_desc': 'Book, reschedule, or cancel appointments with just a few clicks from your personalized dashboard.',
        'feature_3_title': 'Verified Profiles',
        'feature_3_desc': 'Access detailed profiles of verified medical professionals with real patient reviews and ratings.',
        'section_how_title': 'How It Works',
        'step_1_title': 'Find a Doctor',
        'step_1_desc': 'Browse our extensive directory of specialists or use our AI chatbot to find the perfect match.',
        'step_2_title': 'Select Time',
        'step_2_desc': 'Choose a convenient date and time slot that fits your schedule from the doctor\'s live availability.',
        'step_3_title': 'Confirm Booking',
        'step_3_desc': 'Securely confirm your appointment and receive instant notifications and reminders.',
        'cta_title': 'Ready to Start Your Health Journey?',
        'cta_subtitle': 'Join thousands of satisfied patients and start booking appointments today.',
        'btn_join_now': 'Join DocConnect Now',
        'chat_welcome': 'Hello! How can I help you today?',
        'testimonial_title': 'What Our Community Says',
        'testimonial_subtitle': 'Read testimonials from our satisfied patients and doctors',
        'tab_patients': 'Patients',
        'tab_doctors': 'Doctors',
        'faq_title': 'Frequently Asked Questions',
        'faq_subtitle': 'Find answers to common questions about DocConnect',
        'faq_1_q': 'How do I book an appointment on DocConnect?',
        'faq_1_a': 'Simply find a doctor in our directory, select an available time slot, and confirm your booking. It takes less than a minute!',
        'footer_desc': 'DocConnect is a smart healthcare platform dedicated to providing seamless appointment booking and better communication between doctors and patients.',
        'footer_quick_links': 'Quick Links',
        'footer_contact_info': 'Contact Info',
        'page_title_index': 'Home',
        'page_title_doctors': 'Doctors',
        'page_title_appointment': 'Book Appointment'
    },
    'hi': {
        'nav_home': 'होम',
        'nav_doctors': 'डॉक्टर खोजें',
        'nav_appointments': 'अपॉइंटमेंट',
        'nav_contact': 'संपर्क',
        'nav_login': 'लॉगिन',
        'nav_signup': 'साइन अप',
        'nav_book': 'अपॉइंटमेंट बुक करें',
        'hero_title': 'आपका स्वास्थ्य, <span>हमारी प्राथमिकता</span>',
        'hero_subtitle': 'टॉप-रेटेड डॉक्टरों से जुड़ें और सेकंडों में अपॉइंटमेंट बुक करें। बेहतर स्वास्थ्य की आपकी यात्रा यहीं से शुरू होती है।',
        'btn_get_started': 'शुरू करें',
        'btn_how_it_works': 'यह कैसे काम करता है',
        'stat_doctors': 'सत्यापित डॉक्टर',
        'stat_patients': 'खुश मरीज',
        'stat_rating': 'औसत रेटिंग',
        'section_features_title': 'DocConnect क्यों चुनें?',
        'section_features_subtitle': 'हम मरीजों और डॉक्टरों दोनों के लिए सबसे सहज और सुरक्षित स्वास्थ्य देखभाल अनुभव प्रदान करते हैं।',
        'feature_1_title': 'स्मार्ट एआई चैटबॉट',
        'feature_1_desc': 'अपने चिकित्सा प्रश्नों के तुरंत उत्तर प्राप्त करें और हमारे एआई सहायक का उपयोग करके सही डॉक्टर खोजें।',
        'feature_2_title': 'आसान शेड्यूलिंग',
        'feature_2_desc': 'अपने व्यक्तिगत डैशबोर्ड से कुछ ही क्लिक के साथ अपॉइंटमेंट बुक करें, रीशेड्यूल करें या रद्द करें।',
        'feature_3_title': 'सत्यापित प्रोफाइल',
        'feature_3_desc': 'वास्तविक मरीज समीक्षाओं और रेटिंग के साथ सत्यापित चिकित्सा पेशेवरों की विस्तृत प्रोफाइल तक पहुंचें।',
        'section_how_title': 'यह कैसे काम करता है',
        'step_1_title': 'डॉक्टर खोजें',
        'step_1_desc': 'विशेषज्ञों की हमारी विस्तृत निर्देशिका ब्राउज़ करें या सही मिलान खोजने के लिए हमारे एआई चैटबॉट का उपयोग करें।',
        'step_2_title': 'समय चुनें',
        'step_2_desc': 'डॉक्टर की लाइव उपलब्धता से अपनी सुविधा के अनुसार तारीख और समय चुनें।',
        'step_3_title': 'बुकिंग की पुष्टि करें',
        'step_3_desc': 'सुरक्षित रूप से अपने अपॉइंटमेंट की पुष्टि करें और तुरंत सूचनाएं और रिमाइंडर प्राप्त करें।',
        'cta_title': 'अपनी स्वास्थ्य यात्रा शुरू करने के लिए तैयार हैं?',
        'cta_subtitle': 'हजारों संतुष्ट मरीजों से जुड़ें और आज ही अपॉइंटमेंट बुक करना शुरू करें।',
        'btn_join_now': 'अभी DocConnect से जुड़ें',
        'chat_welcome': 'नमस्ते! मैं आज आपकी कैसे मदद कर सकता हूँ?',
        'testimonial_title': 'हमारा समुदाय क्या कहता है',
        'testimonial_subtitle': 'हमारे संतुष्ट मरीजों और डॉक्टरों के प्रशंसापत्र पढ़ें',
        'tab_patients': 'मरीज',
        'tab_doctors': 'डॉक्टर',
        'faq_title': 'अक्सर पूछे जाने वाले प्रश्न',
        'faq_subtitle': 'DocConnect के बारे में सामान्य प्रश्नों के उत्तर खोजें',
        'faq_1_q': 'मैं DocConnect पर अपॉइंटमेंट कैसे बुक करूं?',
        'faq_1_a': 'बस हमारी निर्देशिका में एक डॉक्टर खोजें, एक उपलब्ध समय स्लॉट चुनें, और अपनी बुकिंग की पुष्टि करें। इसमें एक मिनट से भी कम समय लगता है!',
        'footer_desc': 'DocConnect एक स्मार्ट हेल्थकेयर प्लेटफॉर्म है जो डॉक्टरों और मरीजों के बीच निर्बाध अपॉइंटमेंट बुकिंग और बेहतर संचार प्रदान करने के लिए समर्पित है।',
        'footer_quick_links': 'त्वरित लिंक',
        'footer_contact_info': 'संपर्क विवरण',
        'page_title_index': 'होम',
        'page_title_doctors': 'डॉक्टर',
        'page_title_appointment': 'अपॉइंटमेंट बुक करें'
    },
    'or': {
        'nav_home': 'ହୋମ',
        'nav_doctors': 'ଡାକ୍ତର ଖୋଜନ୍ତୁ',
        'nav_appointments': 'ଅପଏଣ୍ଟମେଣ୍ଟ',
        'nav_contact': 'ସମ୍ପର୍କ',
        'nav_login': 'ଲଗ୍ ଇନ୍',
        'nav_signup': 'ସାଇନ୍ ଅପ୍',
        'nav_book': 'ଅପଏଣ୍ଟମେଣ୍ଟ ବୁକିଂ',
        'hero_title': 'ଆପଣଙ୍କ ସ୍ୱାସ୍ଥ୍ୟ, <span>ଆମର ପ୍ରାଥମିକତା</span>',
        'hero_subtitle': 'ଶ୍ରେଷ୍ଠ ଡାକ୍ତରମାନଙ୍କ ସହିତ ଯୋଗାଯୋଗ କରନ୍ତୁ ଏବଂ କିଛି ସେକେଣ୍ଡ ମଧ୍ୟରେ ଅପଏଣ୍ଟମେଣ୍ଟ ବୁକ କରନ୍ତୁ | ସୁସ୍ଥ ଜୀବନ ପାଇଁ ଆପଣଙ୍କର ଯାତ୍ରା ଏଠାରୁ ଆରମ୍ଭ ହୁଏ |',
        'btn_get_started': 'ଆରମ୍ଭ କରନ୍ତୁ',
        'btn_how_it_works': 'ଏହା କିପରି କାମ କରେ',
        'stat_doctors': 'ସତ୍ୟାପିତ ଡାକ୍ତର',
        'stat_patients': 'ଖୁସି ରୋଗୀ',
        'stat_rating': 'ହାରାହାରି ରେଟିଂ',
        'section_features_title': 'DocConnect କାହିଁକି ବାଛିବେ?',
        'section_features_subtitle': 'ଆମେ ରୋଗୀ ଏବଂ ଡାକ୍ତର ଉଭୟଙ୍କ ପାଇଁ ସବୁଠାରୁ ସହଜ ଏବଂ ସୁରକ୍ଷିତ ସ୍ୱାସ୍ଥ୍ୟସେବା ଅନୁଭୂତି ପ୍ରଦାନ କରୁଛୁ |',
        'feature_1_title': 'ସ୍ମାର୍ଟ ଏଆଇ ଚାଟବଟ୍',
        'feature_1_desc': 'ଆପଣଙ୍କର ଚିକିତ୍ସା ସମ୍ବନ୍ଧୀୟ ପ୍ରଶ୍ନର ତୁରନ୍ତ ଉତ୍ତର ପାଆନ୍ତୁ ଏବଂ ଆମର ଏଆଇ ସହାୟକ ବ୍ୟବହାର କରି ସଠିକ୍ ଡାକ୍ତର ଖୋଜନ୍ତୁ |',
        'feature_2_title': 'ସହଜ ସିଡ୍ୟୁଲିଂ',
        'feature_2_desc': 'ଆପଣଙ୍କର ବ୍ୟକ୍ତିଗତ ଡ୍ୟାସବୋର୍ଡରୁ ମାତ୍ର କିଛି କ୍ଲିକ୍ ସହିତ ଅପଏଣ୍ଟମେଣ୍ଟ ବୁକ୍ କରନ୍ତୁ, ପରିବର୍ତ୍ତନ କରନ୍ତୁ କିମ୍ବା ବାତିଲ୍ କରନ୍ତୁ |',
        'feature_3_title': 'ସତ୍ୟାପିତ ପ୍ରୋଫାଇଲ୍',
        'feature_3_desc': 'ରୋଗୀଙ୍କ ସମୀକ୍ଷା ଏବଂ ରେଟିଂ ସହିତ ସତ୍ୟାପିତ ଚିକିତ୍ସା ପ୍ରଫେସନାଲମାନଙ୍କର ବିସ୍ତୃତ ପ୍ରୋଫାଇଲ୍ ପାଆନ୍ତୁ |',
        'section_how_title': 'ଏହା କିପରି କାମ କରେ',
        'step_1_title': 'ଡାକ୍ତର ଖୋଜନ୍ତୁ',
        'step_1_desc': 'ବିଶେଷଜ୍ଞଙ୍କ ନିର୍ଦ୍ଦେଶିକା ବ୍ରାଉଜ୍ କରନ୍ତୁ କିମ୍ବା ଉପଯୁକ୍ତ ଡାକ୍ତର ପାଇବା ପାଇଁ ଆମର ଏଆଇ ଚାଟ୍ ବଟ୍ ବ୍ୟବହାର କରନ୍ତୁ |',
        'step_2_title': 'ସମୟ ବାଛନ୍ତୁ',
        'step_2_desc': 'ଡାକ୍ତରଙ୍କ ଉପଲବ୍ଧତା ଅନୁଯାୟୀ ଆପଣଙ୍କ ସୁବିଧା ଅନୁସାରେ ତାରିଖ ଏବଂ ସମୟ ବାଛନ୍ତୁ |',
        'step_3_title': 'ବୁକିଂ ନିଶ୍ଚିତ କରନ୍ତୁ',
        'step_3_desc': 'ସୁରକ୍ଷିତ ଭାବରେ ଆପଣଙ୍କର ଅପଏଣ୍ଟମେଣ୍ଟ ନିଶ୍ଚିତ କରନ୍ତୁ ଏବଂ ତୁରନ୍ତ ନୋଟିଫିକେସନ୍ ପାଆନ୍ତୁ |',
        'cta_title': 'ଆପଣଙ୍କର ସ୍ୱାସ୍ଥ୍ୟ ଯାତ୍ରା ଆରମ୍ଭ କରିବା ପାଇଁ ପ୍ରସ୍ତୁତ କି?',
        'cta_subtitle': 'ହଜାର ହଜାର ସନ୍ତୁଷ୍ଟ ରୋଗୀଙ୍କ ସହିତ ଯୋଗ ଦିଅନ୍ତୁ ଏବଂ ଆଜି ହିଁ ଅପଏଣ୍ଟମେଣ୍ଟ ବୁକିଂ ଆରମ୍ଭ କରନ୍ତୁ |',
        'btn_join_now': 'ବର୍ତ୍ତମାନ DocConnect ରେ ଯୋଗ ଦିଅନ୍ତୁ',
        'chat_welcome': 'ନମସ୍କାର! ମୁଁ ଆଜି ଆପଣଙ୍କୁ କିପରି ସାହାଯ୍ୟ କରିପାରିବି?',
        'testimonial_title': 'ଆମ ସମ୍ପ୍ରଦାୟ କଣ କହେ',
        'testimonial_subtitle': 'ଆମର ସନ୍ତୁଷ୍ଟ ରୋଗୀ ଏବଂ ଡାକ୍ତରମାନଙ୍କର ପ୍ରଶଂସାପତ୍ର ପଢନ୍ତୁ',
        'tab_patients': 'ରୋଗୀ',
        'tab_doctors': 'ଡାକ୍ତର',
        'faq_title': 'ସାଧାରଣ ପ୍ରଶ୍ନ',
        'faq_subtitle': 'DocConnect ବିଷୟରେ ସାଧାରଣ ପ୍ରଶ୍ନର ଉତ୍ତର ପାଆନ୍ତୁ',
        'faq_1_q': 'ମୁଁ DocConnect ରେ କିପରି ଅପଏଣ୍ଟମେଣ୍ଟ ବୁକ୍ କରିବି?',
        'faq_1_a': 'ଆମ ନିର୍ଦ୍ଦେଶିକାରେ ଜଣେ ଡାକ୍ତର ଖୋଜନ୍ତୁ, ଏକ ଉପଲବ୍ଧ ସମୟ ବାଛନ୍ତୁ ଏବଂ ଆପଣଙ୍କର ବୁକିଂ ନିଶ୍ଚିତ କରନ୍ତୁ | ଏହା ଏକ ମିନିଟରୁ କମ୍ ସମୟ ନିଏ!',
        'footer_desc': 'DocConnect ହେଉଛି ଏକ ସ୍ମାର୍ଟ ହେଲ୍ଥକେୟାର ପ୍ଲାଟଫର୍ମ ଯାହା ଡାକ୍ତର ଏବଂ ରୋଗୀଙ୍କ ମଧ୍ୟରେ ନିରନ୍ତର ଅପଏଣ୍ଟମେଣ୍ଟ ବୁକିଂ ଏବଂ ଉତ୍ତମ ଯୋଗାଯୋଗ ପ୍ରଦାନ ପାଇଁ ଉତ୍ସର୍ଗୀକୃତ |',
        'footer_quick_links': 'କ୍ୱିକ ଲିଙ୍କ୍',
        'footer_contact_info': 'ଯୋଗାଯୋଗ ବିବରଣୀ',
        'page_title_index': 'ହୋମ',
        'page_title_doctors': 'ଡାକ୍ତର',
        'page_title_appointment': 'ଅପଏଣ୍ଟମେଣ୍ଟ ବୁକିଂ',
        'page_title_login': 'ଲଗ୍ ଇନ୍',
        'nav_signup': 'ସାଇନ୍ ଅପ୍'
    }
};

if (typeof module !== 'undefined' && module.exports) {
    module.exports = translations;
} else {
    window.translations = translations;
}
